article/urls.py
from django.conf.urls import url
from . import views
from . import list_views

urlpatterns = [
    url(r'^article_column/$', views.article_column, name="article_column"),
    url(r'^rename_article_column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^delete_article_column/$', views.delete_article_column, name="delete_article_column"),
    url(r'^article_post/$', views.article_post, name="article_post"),
    url(r'^article_list/$', views.article_list, name="article_list"),
    url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^delete_article/$', views.delete_article, name="delete_article"),
    url(r'^redit_article/(?P<article_id>[-\w]+)/$', views.redit_article, name="redit_article"),
    url(r'^list_article_titles/$', list_views.article_titles, name="list_article_titles"),
    url(r'^list_article_titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^list_article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^like_article/$', list_views.like_article, name="like_article"),
    url(r'^article_tag/$', views.article_tag, name="article_tag"),
    url(r'^del_article_tag/$', views.del_article_tag, name="del_article_tag"),
]
app_name = 'article'

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail")
]
app_name = 'blog'

demo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^pwd_reset/', include('password_reset.urls'), name='pwd_reset'),
    url(r'^article/', include('article.urls'), name='article'),
    url(r'^image/', include('image.urls'), name='image'),
    url(r'^course/', include('course.urls'), name='course'),
    url(r'^home/', TemplateView.as_view(template_name="home.html")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_created=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag',on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    user_like = models.ManyToManyField(User, related_name='article_like', blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag')

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)  # 对这两个字段建立索引

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn, ArticlePost, ArticleTag
from .form import ArticleColumnForm, ArticlePostForm, ArticleTagForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json


# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)  # 根据当前用户筛选出和当前用户一直的文章的元组
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {"columns": columns, "column_form": column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')


@login_required(login_url='/account/login/')
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def delete_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)  # 获取表单数据
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)  # 将表单对象转换成实体对象，暂时不提交数据库
                new_article.author = request.user  # 将当前用户对象赋值给实体对象
                new_article.column = request.user.article_column.get(
                    id=request.POST['column_id'])  # 通过外键将column对象赋值给实体对象
                new_article.save()
                tags = request.POST['tags']
                print(tags)
                if tags:
                    for tag in json.loads(tags):
                        tag = request.user.tag.get(tag=tag)
                        new_article.article_tag.add(tag)
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_tags = request.user.tag.all()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns,
                       "article_tags": article_tags})


@login_required(login_url='/account/login/')
@csrf_exempt
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 4)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = Paginator.page(self=paginator, number=1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


@login_required(login_url='/account/login/')
@csrf_exempt
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login/')
@csrf_exempt
def delete_article(request):
    article_id = request.POST['article_id']
    try:
        line = ArticlePost.objects.get(id=article_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('0')


@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()  # 获取当前用户的所有columns
        article = ArticlePost.objects.get(id=article_id)  # 获取当前需要修改的article
        this_article_form = ArticlePostForm(initial={"title": article.title})  # 获取当前获取当前需要修改的article主题的input对象
        this_article_column = article.column  # 获取column的input对象
        return render(request, 'article/column/redit_article.html',
                      {"article": article, "article_columns": article_columns, "this_article_form": this_article_form,
                       "this_article_column": this_article_column})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')


@login_required(login_url='/account/login/')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tag = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html',
                      {"article_tag_form": article_tag_form, "article_tag": article_tag})
    if request.method == "POST":
        article_tag_form = ArticleTagForm(data=request.POST)
        if article_tag_form.is_valid():
            try:
                new_tag = article_tag_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('the data cannot be save')
        else:
            return HttpResponse('sorry,the form is not valid')


@login_required(login_url='/account/login/')
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['id']
    try:
        article_tag = ArticleTag.objects.filter(id=tag_id)
        article_tag.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

templates/article/list/article_detail.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% load article_tags %}
{% block title %}article detail{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
{% endblock %}
{% block js %}
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd.markdownToHTML("editor_view", {
                htmlDecode: "style,script,iframe",
                emoji: true,
                taskList: true,
                tex: true,
                flowChart: true,
                sequenceDiagram: true,
            });
        });
    </script>
    <script type="text/javascript">
        function like_article(id, action) {
            $.post('{% url "article:like_article" %}', {"id": id, "action": action}, function (data) {
                if (data == 1) {
                    layer.msg('感谢点赞');
                    window.location.reload();
                } else {
                    layer.msg('我会继续努力');
                    window.location.reload();
                }
            })
        }
    </script>
{% endblock %}
{% with total_like=article.user_like.count  user_like=article.user_like.all %}
    {% block content %}
        <div class="container">
            <div class="col-md-9">
                <header>
                    <h1>标题:{{ article.title }}</h1>
                    <p>作者:<a
                            href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                        <span style="margin-left: 20px"
                              class="glyphicon glyphicon-thumbs-up">{{ total_like }} like {{ total_like|pluralize }}</span>
                        <span style="margin-left: 20px">{{ total_views }} view {{ total_views|pluralize }}</span>
                    </p>
                    <p>
                        <span style="margin-right: 10px"><strong>tags:</strong></span>{{ article.article_tag.all |join:',' }}
                    </p>
                </header>
                <div id="editor_view">
                                        <textarea id="append_test" style="display: none">
                                            {{ article.body }}
                                        </textarea>
                    {#                    {{ article.body|markdown }}#}
                </div>
                <div>
                    <p class="text-center">
                        <a onclick="like_article({{ article.id }},'like' )" href="#"><span
                                class="glyphicon glyphicon-thumbs-up">like</span></a><span>|</span>
                        <a onclick="like_article({{ article.id }},'unlike' )" href="#"><span
                                class="glyphicon glyphicon-thumbs-down">unlike</span></a>
                    </p>
                </div>
                <div>
                    <p class="text-center"><strong>点赞本文的读者</strong></p>
                    {% for user in article.user.user_like.all %}\
                        <p class="text-center">{{ user.username }}</p>
                    {% empty %}
                        <p class="text-center">还没有人对此文章表态</p>
                    {% endfor %}
                </div>
                <hr>
                <div>
                    <h3><span class="glyphicon glyphicon-bullhorn"></span> 本文有{{ comments.count }}评论 </h3>
                    {% for commnet in article.comments.all %}
                        <div>
                            <p><strong>{{ commnet.commentator }}</strong> 说: </p>
                            <p style="margin-left: 40px">{{ commnet.body }}</p>
                        </div>
                    {% empty %}
                        <p>没有评论</p>
                    {% endfor %}
                    <h3><span class="glyphicon glyphicon-send"></span> 看文章，发评论，不要沉默 </h3>
                    <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label"> 评论员 </label>
                            <div class="col-sm-10">
                                {{ comment_form.commentator }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label"> 评论 </label>
                            <div class="col-sm-10">
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <p><input type="submit" name="" value="发布" class="btn btn-primary btn-lg"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3">
                <p class="text-center">
                <h3>最受欢迎的文章</h3></p>
                <ol>
                    {% for article in most_viewed %}
                        <li>
                            <a href="{{ article.get_url_path }}">{{ article.title }}</a>
                        </li>
                    {% endfor %}
                </ol>
                <hr>
                <p class="text-center">
                <h3>最新文章</h3></p>
                {% latest_articles 4 %}
                <hr>
                <p class="text-center">
                <h3>最多评论文章</h3></p>
                {% most_commented_articles 4 %}
                <hr>
                <p class="text-center">
                <h3>推荐相似的文章</h3></p>
                <ul>
                    {% for similar in similar_articles %}
                        <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a></p>
                    {% empty %}
                        <p>sorry,没有相似的文章</p>
                    {% endfor %}
                </ul>
            </div>
        </div>
        </div>
        </div>

    {% endblock %}
{% endwith %}

templates/article/list/article_title.html
{% extends 'article/base.html' %}
{% load article_tags %}
{% block title %}articles{% endblock %}
{% block css %}{% endblock %}
{% block js %}{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>阅读，丰富头脑，善化行为</h1>
        <p>这里有{% total_articles %}篇文章供你阅读</p>
    </div>
    <div class="container">
        {% for article in articles %}
            <div class="list-group">
                <a href="{{ article.get_url_path }}" class="list-group-item active">
                    <h4 class="list-group-item-heading">{{ article.title }}</h4></a>
                <p class="list-group-item-text">作者:<a
                        href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                </p>
                <p class="list-group-item-text">概要:{{ article.body|slice:'70' |linebreaks }}</p>

            </div>
        {% endfor %}
        {% include 'article/paginator.html' %}
    </div>
{% endblock %}

templates/article/list/author_article.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% load article_tags %}
{% block title %}articles{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>阅读，丰富头脑，善化行为</h1>

    </div>
    <div class="container">
        <div class="col-md-8">
            {% for article in articles %}
                <div class="list-group">
                    <a href="{{ article.get_url_path }}" class="list-group-item active">
                        <h4 class="list-group-item-heading">{{ article.title }}</h4></a>
                    <p class="list-group-item-text">作者:<a
                            href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                    </p>
                    <p class="list-group-item-text">概要:{{ article.body|slice:'70' |linebreaks }}</p>

                </div>
            {% endfor %}
            {% include 'article/paginator.html' %}

        </div>
        <div class="col-md-4">
            <div>
                {% if userinfo.photo %}
                    <img src="{{ userinfo.photo|striptags }}" class="img-circle" width="150px" height="150px"
                         id="my_photo" name="user_face">
                {% else %}
                    <img src="{% static 'images/gaos.jpg' %}" name="user_face" class="img-circle" id="my_photo">
                {% endif %}
            </div>
            <div>
                <p>{{ user.username }}</p>
                {% if userinfo %}
                    <p>{{ userinfo.company }}</p>
                    <p>{{ userinfo.school }}</p>
                    <div>
                        <p>共发表文章{% author_total_article user %}篇</p>
                    </div>
                {% else %}
                    <p>这个作者太懒，什么也没填写</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
        <li>
            <a href="{{ article.get_url_path }}">{{ article.title }}</a>
        </li>
    {% empty %}
    {% endfor %}
</ul>

templates/article/list/most_commented_articles.html
{% load article_tags %}
<ul>
    {% for article in most_commented_articles %}
        <li>
            <a href="{{ article.get_url_path }}">{{ article.title }}</a>
        </li>
    {% empty %}
    {% endfor %}
</ul>