account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
    # url(r'^login/$', views.user_login, name='user_login'),
    url(r'^login/$', auth_views.login, name="user_login"),
    url(r'^new-login/$', auth_views.login, {'template_name': 'account/login.html'}),
    # url(r'^logout/$', auth_views.logout, name='user_logout'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'account/logout.html'}, name='user_logout'),
    url(r'^register/$', views.register, name='user_register'),

    url(r'^password_change/$', auth_views.password_change,
        {"post_change_redirect": '/account/password_change_done'},
        name='password_change'),

    url(r'^password_change_done/$', auth_views.password_change_done,
        {"template_name": 'account/password_change_done.html'},
        name='password_change_done'),

    url(r'^password_reset/$', auth_views.password_reset, {"template_name": "account/password_change_form.html",
                                                          "email_template_name": "account/password_reset_email.html",
                                                          "subject_template_name": "account/password_change_subject.txt",
                                                          "post_reset_redirect": "/account/password_reset_done"},
        name="password_reset"),

    url(r'^password_reset_done/$', auth_views.password_reset_done,
        {"template_name": "account/password_reset_done.html"}, name='password_reset_done'),

    url(r'^password_reset_confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name": 'account/password_reset_confirm.html',
         "post_reset_redirect": "/account/password_reset_complete"}, name='password_reset_confirm'),

    url(r'^password_reset_complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),

    url(r'^my_information/$', views.myself, name="my_information"),

    url(r'^edit_myself_information/$', views.myself_edit, name="edit_myself_information"),

    url(r'^my_image/$', views.my_image, name="my_image"),
]

article/urls.py
from django.conf.urls import url
from . import views
from . import list_views

urlpatterns = [
    url(r'^article_column/$', views.article_column, name="article_column"),
    url(r'^rename_article_column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^delete_article_column/$', views.delete_article_column, name="delete_article_column"),
    url(r'^article_post/$', views.article_post, name="article_post"),
    url(r'^article_list/$', views.article_list, name="article_list"),
    url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^delete_article/$', views.delete_article, name="delete_article"),
    url(r'^redit_article/(?P<article_id>[-\w]+)/$', views.redit_article, name="redit_article"),
    url(r'^list_article_titles/$', list_views.article_titles, name="list_article_titles"),
    url(r'^list_article_titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^list_article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^like_article/$', list_views.like_article, name="like_article"),
    url(r'^article_tag/$', views.article_tag, name="article_tag"),
    url(r'^del_article_tag/$', views.del_article_tag, name="del_article_tag"),
]
app_name = 'article'

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail")
]
app_name = 'blog'

course/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'course'
urlpatterns = [
    url('^about/$', TemplateView.as_view(template_name='course/about.html'), name='about'),
    url('^course_list/$', views.CourseListView.as_view(), name='course_list'),
    url('^course_manage/$', views.ManageCourseListView.as_view(), name='course_manage'),
    url('^course_created/$', views.CreatedCourseView.as_view(), name='course_created'),
    url('^course_delete/(?P<pk>\d+)/$', views.DeleteCourseView.as_view(), name='course_delete'),
    url('^lesson_created/$', views.CreatedLessionView.as_view(), name='lesson_created'),
    url('^list_lesson/(?P<course_id>\d+)/$', views.ListLessonsView.as_view(), name='list_lesson'),
    url('^detail_lesson/(?P<lesson_id>\d+)/$', views.DetailLessonview.as_view(), name='detail_lesson'),
]

demo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^pwd_reset/', include('password_reset.urls'), name='pwd_reset'),
    url(r'^article/', include('article.urls'), name='article'),
    url(r'^image/', include('image.urls'), name='image'),
    url(r'^course/', include('course.urls'), name='course'),
    url(r'^home/', TemplateView.as_view(template_name="home.html")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/urls.py
from django.conf.urls import url
from image import views

urlpatterns = [
    url(r'^list_images/$', views.list_image, name="list_images"),
    url(r'^upload_image/$', views.upload_image, name="upload_image"),
    url(r'^del_image/$', views.del_image, name="del_image"),
    url(r'^falls_images/$', views.falls_images, name="falls_images"),
]
app_name = 'image'

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<div class="container">
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
    {% block javascript %}{% endblock %}
</div>
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy rigtht www.itdiffer.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">

        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="http://www.itdiffer.com">
                    <img src="{% static 'images/logo_coffe_cat.jpg' %}" width="100px" height="100%">
                </a>
            </div>
            <div>
                <ul class="nav navbar-nav" role="navigation">
                    <li><a href="{% url 'course:about' %}">ABOUT</a></li>
                    <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                    <li><a href="{% url 'article:list_article_titles' %}">文章</a></li>
                    <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                    <li><a href="{% url 'course:course_list' %}">课程</a></li>
                    <li><a href="{% url 'course:course_manage' %}">课程管理</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                    {% if user.is_authenticated %}
                        <li>
                            <div class="dropdown" style="margin-top: 8px">
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                        data-toggle="dropdown">
                                    {{ user.username }}<span class="caret"></span>
                                </button>
                                <ul>
                                    <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                    <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                                </ul>
                            </div>
                        </li>
                        <li><a href="#">{{ user.username }}</a></li>
                        <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                        <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                    {% else %}
                        <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                        <li><a href="{% url 'account:user_register' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>WELCOME YOU</h1>
        <h3>Life is short .You need Python</h3>
        <h2>Django makes it easier to bulid better Web apps more quickly and with less code</h2>
    </div>
    <img src="{% static 'images/python.jpg' %}">
{% endblock %}